### PR TITLE
issue #24: coverage tests

### LINKED ISSUE #24: Add python tests coverage workflow
https://github.com/ai-cfia/github-workflows/pull/5

### PR DESCRIPTION
**Pull request by ThomasCardin**
Testing the coverage of fertiscan-backend
- Closes #24

### CODE REVIEW

**Review by snakedye — APPROVED** [review]
There doesn't seem to be anything in this PR.

**Comment by ThomasCardin** [comment]
Indeed, workflows are not starting :(

**Comment by ThomasCardin** [comment]
image

@snakedye , we have just added test coverage to the Python codebase. We need the coverage to be at least 80% for the workflow to pass. Would you prefer that I create an issue or leave this PR open so you can apply the necessary changes? Let me know what works best for you.

**Comment by snakedye** [comment]
There's not a lot of PRs. We can merge this now and then I'll make a PR to correct main.

**Pull request merged**
