### PR TITLE
Issue #164: updates imports/dependencies with new monorepo modules structure

### PR DESCRIPTION
**Pull request by SonOfLope**
ref #164

### CODE REVIEW

**Comment by k-allagbe** [comment]
I get 
```
    ~/gi/ailab-datastore  on   151-inspector-notes ⇣2 *4 ?4  pip install git+https://github.com/ai-cfia/ailab-datastore.git@v1.0.0-fertiscan-datastore

Collecting git+https://github.com/ai-cfia/ailab-datastore.git@v1.0.0-fertiscan-datastore
  Cloning https://github.com/ai-cfia/ailab-datastore.git (to revision v1.0.0-fertiscan-datastore) to /private/var/folders/43/4zssf0gs6sj_j_kzmzgdzx0m0000gn/T/pip-req-build-r1i7llb6
  Running command git clone --filter=blob:none --quiet https://github.com/ai-cfia/ailab-datastore.git /private/var/folders/43/4zssf0gs6sj_j_kzmzgdzx0m0000gn/T/pip-req-build-r1i7llb6
  WARNING: Did not find branch or tag 'v1.0.0-fertiscan-datastore', assuming revision or ref.
  Running command git checkout -q v1.0.0-fertiscan-datastore
  error: pathspec 'v1.0.0-fertiscan-datastore' did not match any file(s) known to git
  error: subprocess-exited-with-error
  
  × git checkout -q v1.0.0-fertiscan-datastore did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× git checkout -q v1.0.0-fertiscan-datastore did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by SonOfLope** [comment]
> I get
> 
> ```
>  ...>  pip install git+https://github.com/ai-cfia/ailab-datastore.git@v1.0.0-fertiscan-datastore
> 
> Collecting git+https://github.com/ai-cfia/ailab-datastore.git@v1.0.0-fertiscan-datastore
>   Cloning https://github.com/ai-cfia/ailab-datastore.git (to revision v1.0.0-fertiscan-datastore) to /private/var/folders/43/4zssf0gs6sj_j_kzmzgdzx0m0000gn/T/pip-req-build-r1i7llb6
>   Running command git clone --filter=blob:none --quiet https://github.com/ai-cfia/ailab-datastore.git /private/var/folders/43/4zssf0gs6sj_j_kzmzgdzx0m0000gn/T/pip-req-build-r1i7llb6
>   WARNING: Did not find branch or tag 'v1.0.0-fertiscan-datastore', assuming revision or ref.
>   Running command git checkout -q v1.0.0-fertiscan-datastore
>   error: pathspec 'v1.0.0-fertiscan-datastore' did not match any file(s) known to git
>   error: subprocess-exited-with-error
>   
>   × git checkout -q v1.0.0-fertiscan-datastore did not run successfully.
>   │ exit code: 1
>   ╰─> See above for output.
>   
>   note: This error originates from a subprocess, and is likely not a problem with pip.
> error: subprocess-exited-with-error
> 
> × git checkout -q v1.0.0-fertiscan-datastore did not run successfully.
> │ exit code: 1
> ╰─> See above for output.
> 
> note: This error originates from a subprocess, and is likely not a problem with pip.
> ```

Yes thats why PR was still in draft. Should work now

**Comment by k-allagbe** [comment]
Everything looks good. The tests will fail basically because v1.0.0 is not up to date. So our next version should fix them. How nice is this? Thank you.

**Review by k-allagbe — APPROVED** [review]
Please let's wait for an up to date version before merging to main.

**Comment by k-allagbe** [comment]
All good now.

**Pull request merged**
